version: "2"
services:
    jenkins:
        container_name: jenkins
        image: shukriadams/dockerjenkinsdocker:2.213
        restart: unless-stopped
        ports:
        - "8085:8080"
        volumes:
        - ./data:/var/jenkins_home/:rw
        - /var/run/docker.sock:/var/run/docker.sock:rw